<?php $pays = [
["id" => 1, "pays" => "Afghanistan"],
["id" => 2, "pays" => "Albania"],
["id" => 3, "pays" => "Algeria"],
["id" => 4, "pays" => "Andorra"],
["id" => 5, "pays" => "Angola"],
["id" => 6, "pays" => "Argentina"],
["id" => 7, "pays" => "Armenia"],
["id" => 8, "pays" => "Australia"],
["id" => 9, "pays" => "Austria"],
["id" => 10, "pays" => "Azerbaijan"],
["id" => 11, "pays" => "Bahamas"],
["id" => 12, "pays" => "Bahrain"],
["id" => 13, "pays" => "Bangladesh"],
["id" => 14, "pays" => "Barbados"],
["id" => 15, "pays" => "Belarus"],
["id" => 16, "pays" => "Belgium"],
["id" => 17, "pays" => "Belize"],
["id" => 18, "pays" => "Benin"],
["id" => 19, "pays" => "Bhutan"],
["id" => 20, "pays" => "Bolivia"],
["id" => 21, "pays" => "Bosnia and Herzegovina"],
["id" => 22, "pays" => "Botswana"],
["id" => 23, "pays" => "Brazil"],
["id" => 24, "pays" => "Brunei"],
["id" => 25, "pays" => "Bulgaria"],
["id" => 26, "pays" => "Burkina Faso"],
["id" => 27, "pays" => "Burundi"],
["id" => 28, "pays" => "Cabo Verde"],
["id" => 29, "pays" => "Cambodia"],
["id" => 30, "pays" => "Cameroon"],
["id" => 31, "pays" => "Canada"],
["id" => 32, "pays" => "Central African Republic"],
["id" => 33, "pays" => "Chad"],
["id" => 34, "pays" => "Chile"],
["id" => 35, "pays" => "China"],
["id" => 36, "pays" => "Colombia"],
["id" => 37, "pays" => "Comoros"],
["id" => 38, "pays" => "Congo (Congo-Brazzaville)"],
["id" => 39, "pays" => "Costa Rica"],
["id" => 40, "pays" => "Croatia"],
["id" => 41, "pays" => "Cuba"],
["id" => 42, "pays" => "Cyprus"],
["id" => 43, "pays" => "Czech Republic"],
["id" => 44, "pays" => "Democratic Republic of the Congo"],
["id" => 45, "pays" => "Denmark"],
["id" => 46, "pays" => "Djibouti"],
["id" => 47, "pays" => "Dominica"],
["id" => 48, "pays" => "Dominican Republic"],
["id" => 49, "pays" => "Ecuador"],
["id" => 50, "pays" => "Egypt"]
];