INSERT INTO aem_country (aem_country) VALUES
('Afghanistan'),
('Albanie'),
('Algérie'),
('Andorre'),
('Angola'),
('Antigua-et-Barbuda'),
('Argentine'),
('Arménie'),
('Australie'),
('Autriche'),
('Azerbaïdjan'),
('Bahamas'),
('Bahreïn'),
('Bangladesh'),
('Barbade'),
('Bélarus'),
('Belgique'),
('Belize'),
('Bénin'),
('Bhoutan'),
('Bolivie'),
('Bosnie-Herzégovine'),
('Botswana'),
('Brésil'),
('Brunei'),
('Bulgarie'),
('Burkina Faso'),
('Burundi'),
('Cabo Verde'),
('Cambodge'),
('Cameroun'),
('Canada'),
('Chili'),
('Chine'),
('Chypre'),
('Colombie'),
('Comores'),
('Congo'),
('Congo (République Démocratique)'),
('Corée du Sud'),
('Costa Rica'),
('Croatie'),
('Cuba'),
('Danemark'),
('Djibouti'),
('Dominique'),
('Égypte'),
('Équateur'),
('Érythrée'),
('Espagne'),
('Estonie');